name: C/C++ Build, Static Analysis, and Memory Leak Detection

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'

jobs:
  build-and-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

# Todo change custom flags (like take some as input and define them in the repository you want).
      - name: Build and compile with custom args
        run: |
          mkdir build
          cd build
          cmake .. -DYOUR_CUSTOM_FLAG=ON
          make

  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Run clang-tidy for static analysis
        run: |
          clang-tidy **/*.cpp -- -std=c++17

  memory-leak-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Run Valgrind to check for memory leaks
        run: |
          valgrind --leak-check=full ./build/your_executable