name: Performance Benchmarking

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install benchmark dependencies
        run: |
          pip install pytest pytest-benchmark

      - name: Run performance benchmarks
        run: |
          pytest --benchmark-only